In [1]:
import os
import json
import pandas as pd
from sqlalchemy import create_engine, text

BASE_PATH = r"D:\\pulse\\data\\top\\transaction\\country\\india\\state\\"

In [2]:
state = os.listdir(BASE_PATH)[0]
year = os.listdir(os.path.join(BASE_PATH, state))[0]
file = os.listdir(os.path.join(BASE_PATH, state, year))[0]

with open(os.path.join(BASE_PATH, state, year, file), "r", encoding="utf-8") as f:
    data = json.load(f)

data["data"].keys()

dict_keys(['states', 'districts', 'pincodes'])

In [4]:
rows = []

for state in os.listdir(BASE_PATH):
    state_path = os.path.join(BASE_PATH, state)
    if not os.path.isdir(state_path):
        continue

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if not file.endswith(".json"):
                continue

            quarter = int(file.replace(".json", ""))

            with open(os.path.join(year_path, file), "r", encoding="utf-8") as f:
                content = json.load(f)

            data_block = content.get("data")
            if not data_block:
                continue

            for category in ["states", "districts", "pincodes"]:
                items = data_block.get(category)
                if not items:
                    continue

                for item in items:
                    metric = item.get("metric")

                    # metric can be dict or list
                    if isinstance(metric, list):
                        metric = metric[0] if metric else {}

                    rows.append({
                        "state": state.replace("-", " ").title(),
                        "year": int(year),
                        "quarter": quarter,
                        "entity_type": category[:-1],
                        "entity_name": item.get("entityName"),
                        "txn_count": metric.get("count", 0),
                        "txn_amount": metric.get("amount", 0.0)
                    })

df_top_txn = pd.DataFrame(rows)
df_top_txn.head()

,state,year,quarter,entity_type,entity_name,txn_count,txn_amount
0,Andaman & Nicobar Islands,2018,1,district,south andaman,5688,1.256025e+07
1,Andaman & Nicobar Islands,2018,1,district,nicobars,528,1.139849e+06
2,Andaman & Nicobar Islands,2018,1,district,north and middle andaman,442,9.316631e+05
3,Andaman & Nicobar Islands,2018,1,pincode,744101,1622,2.769298e+06
4,Andaman & Nicobar Islands,2018,1,pincode,744103,1223,2.238042e+06

In [5]:
df_top_txn.shape

(18295, 7)

In [7]:
engine = create_engine(
    "mysql+mysqlconnector://root:Roqmes-tavha0-tirnan@localhost/phonepe_pulse"
)

create_table = """
CREATE TABLE IF NOT EXISTS top_transaction (
    id INT AUTO_INCREMENT PRIMARY KEY,
    state VARCHAR(100),
    year INT,
    quarter INT,
    entity_type VARCHAR(20),
    entity_name VARCHAR(100),
    txn_count BIGINT,
    txn_amount DOUBLE
);
"""

with engine.connect() as conn:
    conn.execute(text(create_table))
    conn.commit()

In [8]:
df_top_txn.to_sql(
    "top_transaction",
    con=engine,
    if_exists="append",
    index=False
)

18295

In [9]:
pd.read_sql("SELECT * FROM top_transaction LIMIT 5", engine)

,id,state,year,quarter,entity_type,entity_name,txn_count,txn_amount
0,1,Andaman & Nicobar Islands,2018,1,district,south andaman,5688,1.256025e+07
1,2,Andaman & Nicobar Islands,2018,1,district,nicobars,528,1.139849e+06
2,3,Andaman & Nicobar Islands,2018,1,district,north and middle andaman,442,9.316631e+05
3,4,Andaman & Nicobar Islands,2018,1,pincode,744101,1622,2.769298e+06
4,5,Andaman & Nicobar Islands,2018,1,pincode,744103,1223,2.238042e+06

In [10]:
BASE_PATH = r"D:\\pulse\\data\\top\\user\\country\\india\\state\\"

In [11]:
rows = []

for state in os.listdir(BASE_PATH):
    state_path = os.path.join(BASE_PATH, state)
    if not os.path.isdir(state_path):
        continue
        
    for year in os.listdir(state_path):
        for file in os.listdir(os.path.join(state_path, year)):
            if not file.endswith(".json"):
                continue
                
            quarter = int(file.replace(".json", ""))
            with open(os.path.join(state_path, year, file), "r", encoding="utf-8") as f:
                content = json.load(f)

            for category in ["districts", "pincodes"]:
                for item in content["data"][category]:
                    rows.append({
                        "state": state.replace("-", " ").title(),
                        "year": int(year),
                        "quarter": quarter,
                        "entity_type": category[:-1],
                        "entity_name": item["name"],
                        "registered_users": item["registeredUsers"]
                    })

df_top_user = pd.DataFrame(rows)
df_top_user.head()

,state,year,quarter,entity_type,entity_name,registered_users
0,Andaman & Nicobar Islands,2018,1,district,south andaman,5846
1,Andaman & Nicobar Islands,2018,1,district,north and middle andaman,632
2,Andaman & Nicobar Islands,2018,1,district,nicobars,262
3,Andaman & Nicobar Islands,2018,1,pincode,744103,1608
4,Andaman & Nicobar Islands,2018,1,pincode,744101,1108

In [12]:
create_table = """
CREATE TABLE IF NOT EXISTS top_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    state VARCHAR(100),
    year INT,
    quarter INT,
    entity_type VARCHAR(20),
    entity_name VARCHAR(100),
    registered_users BIGINT
);
"""

with engine.connect() as conn:
    conn.execute(text(create_table))
    conn.commit()

In [13]:
df_top_user.to_sql(
    "top_user",
    con=engine,
    if_exists="append",
    index=False
)

18296

In [14]:
pd.read_sql("SELECT * FROM top_user LIMIT 5", engine)

,id,state,year,quarter,entity_type,entity_name,registered_users
0,1,Andaman & Nicobar Islands,2018,1,district,south andaman,5846
1,2,Andaman & Nicobar Islands,2018,1,district,north and middle andaman,632
2,3,Andaman & Nicobar Islands,2018,1,district,nicobars,262
3,4,Andaman & Nicobar Islands,2018,1,pincode,744103,1608
4,5,Andaman & Nicobar Islands,2018,1,pincode,744101,1108